add validation
tomyRootstrap/mvd-app pull request #6
Opened 2022-04-08 13:37 UTC by tomyRootstrap

## Links:

https://trello.com/c/TgEdXJuq/6-2-as-a-user-i-should-only-be-able-to-create-a-maximum-of-10-targets-so-the-map-doesnt-get-too-crowded

## What & Why:

In order to limit the users scope action I've added a target creation limit. With this validation our users only can create 10 targets.

## Risks, Mitigation & Rollback:

- [ ] Safe to Revert *check this box if this PR can be reverted without incident*

2022-04-08 15:32 UTC, FlaviaCohen requested changes

2022-04-08 15:32 UTC, FlaviaCohen commented on src/pages/Home/index.js
> +    setIsTargetCreationLimit(false);
If this state initializes as `false` why do you need to execute this set in the useEffect?

2022-04-08 20:19 UTC, alandours commented on src/pages/Home/index.js
>                <Button type="submit">{t('home.create.saveTarget')}</Button>
Here you could also use `isTargetCreationLimit` to disable the button when it's true to prevent calling onSubmit unnecessarily.

2022-04-11 13:05 UTC, tomyRootstrap commented on src/pages/Home/index.js
> +    setIsTargetCreationLimit(false);
this was a mistake, I should removed this code before I made the pr.

2022-04-11 16:23 UTC, alandours approved these changes

2022-04-11 20:41 UTC, FlaviaCohen approved these changes

2022-04-12 12:05 UTC, merged